name: neoalarm
description: "NeoAlarm: Android-first, local-first open source alarm app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

